import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ModalsProvider from "./providers/ModalsProvider";
import { EdgeStoreProvider } from "../lib/edgestore";
import TanstackProvider from "./(dashboard)/_components/TanstackProvide";

const poppins = Poppins({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <TanstackProvider>
          <Toaster richColors />
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
          <ModalsProvider />
        </TanstackProvider>
      </body>
    </html>
  );
}
